set shell := ["bash", "-cu"]

help:
  just --list

build mode target="all":
  case "{{mode}}" in release) case "{{target}}" in server) (cd apps/server && mkdir -p ../../dist/release && go build -trimpath -buildvcs=false -ldflags="-s -w" -o ../../dist/release/server ./cmd/server) ;; desktop) (cd apps/server && mkdir -p ../../dist/release && go build -trimpath -buildvcs=false -ldflags="-s -w" -o ../../dist/release/server ./cmd/server) && (cd apps/desktop && bun install && RIFF_SERVER_PACKAGE_PATH=../../dist/release/server bun run dist) && rm -rf dist/release/desktop && mkdir -p dist/release/desktop && cp -r apps/desktop/dist/package/* dist/release/desktop ;; all) (cd apps/server && mkdir -p ../../dist/release && go build -trimpath -buildvcs=false -ldflags="-s -w" -o ../../dist/release/server ./cmd/server) && (cd apps/desktop && bun install && RIFF_SERVER_PACKAGE_PATH=../../dist/release/server bun run dist) && rm -rf dist/release/desktop && mkdir -p dist/release/desktop && cp -r apps/desktop/dist/package/* dist/release/desktop ;; *) echo "usage: just build [release|debug] [server|desktop|all]" && exit 1 ;; esac ;; debug) case "{{target}}" in server) (cd apps/server && mkdir -p ../../dist/debug && go build -tags debug -gcflags "all=-N -l" -o ../../dist/debug/server ./cmd/server) ;; desktop) (cd apps/server && mkdir -p ../../dist/debug && go build -tags debug -gcflags "all=-N -l" -o ../../dist/debug/server ./cmd/server) && (cd apps/desktop && bun install && RIFF_SERVER_PACKAGE_PATH=../../dist/debug/server bun run dist) && rm -rf dist/debug/desktop && mkdir -p dist/debug/desktop && cp -r apps/desktop/dist/package/* dist/debug/desktop ;; all) (cd apps/server && mkdir -p ../../dist/debug && go build -tags debug -gcflags "all=-N -l" -o ../../dist/debug/server ./cmd/server) && (cd apps/desktop && bun install && RIFF_SERVER_PACKAGE_PATH=../../dist/debug/server bun run dist) && rm -rf dist/debug/desktop && mkdir -p dist/debug/desktop && cp -r apps/desktop/dist/package/* dist/debug/desktop ;; *) echo "usage: just build [release|debug] [server|desktop|all]" && exit 1 ;; esac ;; *) echo "usage: just build [release|debug] [server|desktop|all]" && exit 1 ;; esac

run target="server":
  case "{{target}}" in server) cd apps/server && go run ./cmd/server ;; desktop) (cd apps/server && mkdir -p ../../dist/release && go build -trimpath -buildvcs=false -ldflags="-s -w" -o ../../dist/release/server ./cmd/server) && (cd apps/desktop && bun install && bun run dev) ;; *) echo "usage: just run [server|desktop]" && exit 1 ;; esac

dev target="all":
  case "{{target}}" in server) cd apps/server && air ;; desktop) cd apps/desktop && bun install && RIFF_DEV_ASSUME_SERVER=1 bun run dev ;; all) bash scripts/dev.sh ;; *) echo "usage: just dev [server|desktop]" && exit 1 ;; esac
